name: notes_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  connectivity_plus: ^5.0.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.0
  flutter_slidable_panel: ^1.1.3
  get_it: ^7.6.7
  google_fonts: ^4.0.4
  intl: ^0.18.1
  json_annotation: ^4.9.0
  logging: ^1.0.2
  mockito: ^5.2.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
